version: "3.8"

services:
  visualizador:
    image: visualizador-sistemas:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visualizador-sistemas
    ports:
      - "38520:80"
    restart: unless-stopped
