version: "3.8"

services:
  visualizador:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visualizador-sistemas
    environment:
      PORT: 3000
      SESSION_SECRET: HLZkoIIKEa8YuJR8nRmz7FP4ycz8/41K2aWXjD3PEuHhfZUCwLCkNYNwmIm1eIPCW3XFHP7QXKrWJy4dxbJhkg==
    ports:
      - "38520:3000"
    volumes:
      - painel_data:/app/data
    restart: unless-stopped

volumes:
  painel_data:
